name: 'Hello World from jeanthink'
description: 'Says hello to me'
author: 'jeanthink'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: 'A random number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
   - run: echo Hello ${{ inputs.who-to-greet }}.
     shell: bash
  
   - id: random-number-generator
     run: echo "::set-output name=random-number::$RANDOM"
     shell: bash

   - run: echo "${{github.action_path}}" >> $GITHUB_PATH
     shell: bash
  
   - run: echo "Goodbye $YOU"
     shell: bash
     env:
       YOU: ${{ inputs.who-to-greet }}